package untrusted.manager.um.network;
import untrusted.manager.um.utils.EdgeToEdgeUtil;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import com.google.android.material.appbar.MaterialToolbar;import com.google.android.material.button.MaterialButton;import java.io.*;import java.util.*;import java.util.concurrent.*;
public class S3Activity extends AppCompatActivity{
 private final ExecutorService io=Executors.newSingleThreadExecutor();private final List<S3Client.Entry> entries=new ArrayList<>();private final List<String> names=new ArrayList<>();private ArrayAdapter<String> adapter;private ListView list;private TextView path,status;private S3Client client;private String prefix="/";private android.content.SharedPreferences prefs;private static final int PICK=71;
 private String profilePrefsName(String base){String id=getIntent().getStringExtra("profile_id");return id==null||id.isEmpty()?base:base+"."+id;} protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences(profilePrefsName("s3_profile"),MODE_PRIVATE); SecureNetworkPrefs.migrate(this,prefs,"access","secret","token"); build();}
 private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);MaterialToolbar bar=new MaterialToolbar(this);bar.setTitle("S3 Storage");bar.setNavigationIcon(androidx.appcompat.R.drawable.abc_ic_ab_back_material);bar.setNavigationOnClickListener(v->finish());r.addView(bar);LinearLayout a=new LinearLayout(this);MaterialButton c=btn("Connect"),u=btn("Upload"),m=btn("New folder");c.setOnClickListener(v->connectDialog());u.setOnClickListener(v->pick());m.setOnClickListener(v->mkdir());a.addView(c,new LinearLayout.LayoutParams(0,-2,1));a.addView(u,new LinearLayout.LayoutParams(0,-2,1));a.addView(m,new LinearLayout.LayoutParams(0,-2,1));r.addView(a);path=new TextView(this);path.setPadding(16,12,16,8);path.setOnClickListener(v->{if(!"/".equals(prefix)){int i=prefix.lastIndexOf('/',prefix.length()-2);prefix=i<0?"/":prefix.substring(0,i+1);load();}});r.addView(path);status=new TextView(this);status.setPadding(16,4,16,8);r.addView(status);list=new ListView(this);adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names);list.setAdapter(adapter);list.setOnItemClickListener((p,v,pos,id)->{S3Client.Entry e=entries.get(pos);if(e.directory){prefix=e.key;load();}else download(e);});list.setOnItemLongClickListener((p,v,pos,id)->{menu(entries.get(pos));return true;});r.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(r); EdgeToEdgeUtil.applyContentInsets(this);status.setText("Not connected");}
 private MaterialButton btn(String s){MaterialButton b=new MaterialButton(this);b.setText(s);return b;}
 private EditText e(String s,String h){EditText x=new EditText(this);x.setSingleLine(true);x.setText(s);x.setHint(h);return x;}
 private void connectDialog(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(20,8,20,8);EditText ep=e(getIntent().getStringExtra("profile_endpoint") != null ? getIntent().getStringExtra("profile_endpoint") : prefs.getString("endpoint","https://s3.amazonaws.com"),"Endpoint");EditText reg=e(prefs.getString("region","us-east-1"),"Region");EditText buck=e(prefs.getString("bucket",""),"Bucket");EditText ak=e(SecureNetworkPrefs.get(this,prefs,"access",""),"Access key");EditText sk=e(SecureNetworkPrefs.get(this,prefs,"secret",""),"Secret key");EditText tok=e(SecureNetworkPrefs.get(this,prefs,"token",""),"Session token (optional)");sk.setInputType(129);tok.setInputType(129);v.addView(ep);v.addView(reg);v.addView(buck);v.addView(ak);v.addView(sk);v.addView(tok);new AlertDialog.Builder(this).setTitle("Connect S3").setView(v).setPositiveButton("Connect",(d,w)->connect(ep.getText().toString(),reg.getText().toString(),buck.getText().toString(),ak.getText().toString(),sk.getText().toString(),tok.getText().toString())).setNegativeButton("Cancel",null).show();}
 private void connect(String ep,String reg,String buck,String ak,String sk,String tok){status.setText("Connecting…");io.execute(()->{try{S3Client c=new S3Client(ep,reg,buck,ak,sk,tok);c.list("/");client=c;android.content.SharedPreferences.Editor pe=prefs.edit(); pe.putString("endpoint",ep).putString("region",reg).putString("bucket",buck); SecureNetworkPrefs.put(pe,"access",ak); SecureNetworkPrefs.put(pe,"secret",sk); SecureNetworkPrefs.put(pe,"token",tok); pe.apply();prefix="/";runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->status.setText("Connection failed: "+x.getMessage()));}});}
 private void load(){if(client==null){status.setText("Not connected");return;}path.setText("Path: "+prefix);status.setText("Loading…");io.execute(()->{try{List<S3Client.Entry> x=client.list(prefix);runOnUiThread(()->{entries.clear();entries.addAll(x);names.clear();for(S3Client.Entry e:x)names.add((e.directory?"📁 ":"📄 ")+e.name);adapter.notifyDataSetChanged();status.setText(x.size()+" items");});}catch(Exception e){runOnUiThread(()->status.setText("Load failed: "+e.getMessage()));}});}
 private void pick(){if(client==null){toast("Connect first");return;}startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),PICK);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r!=PICK||c!=RESULT_OK||d==null||d.getData()==null)return;android.net.Uri u=d.getData();NetworkTransferQueue.get().submit("Upload", ()->{File tmp=new File(getCacheDir(),"s3-upload-"+System.currentTimeMillis());try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(tmp)){if(in==null)throw new IOException("Cannot open source");byte[]b=new byte[65536];int n;while((n=in.read(b))!=-1)out.write(b,0,n);String p=u.getPath();String name=new File(p==null?"upload":p).getName();if(name.contains(":"))name="upload";client.upload(tmp,("/".equals(prefix)?"":prefix)+name);tmp.delete();runOnUiThread(this::load);}catch(Exception e){tmp.delete();runOnUiThread(()->status.setText("Upload failed: "+e.getMessage()));}});}
 private void download(S3Client.Entry e){File dir=Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);if(!dir.exists())dir.mkdirs();File target=new File(dir,e.name);if(target.exists())target=new File(dir,System.currentTimeMillis()+"-"+e.name);final File f=target;status.setText("Downloading…");NetworkTransferQueue.get().submit("Download", ()->{try{client.download(e.key,f);runOnUiThread(()->status.setText("Downloaded: "+f.getAbsolutePath()));}catch(Exception x){runOnUiThread(()->status.setText("Download failed: "+x.getMessage()));}});}
 private void mkdir(){if(client==null){toast("Connect first");return;}EditText x=e("","Folder name");new AlertDialog.Builder(this).setTitle("New S3 folder").setView(x).setPositiveButton("Create",(d,w)->io.execute(()->{try{client.mkdir(("/".equals(prefix)?"":prefix)+x.getText().toString().trim());runOnUiThread(this::load);}catch(Exception z){runOnUiThread(()->status.setText("Create failed: "+z.getMessage()));}})).setNegativeButton("Cancel",null).show();}
 private void menu(S3Client.Entry e){new AlertDialog.Builder(this).setTitle(e.name).setItems(new String[]{"Download","Delete","Rename"},(d,w)->{if(w==0)download(e);else if(w==1)io.execute(()->{try{client.delete(e.key);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->status.setText("Delete failed: "+x.getMessage()));}});else rename(e);}).show();}
 private void rename(S3Client.Entry e){EditText x=e(e.name,"New name");new AlertDialog.Builder(this).setTitle("Rename").setView(x).setPositiveButton("Rename",(d,w)->io.execute(()->{try{String n=x.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException("Name required");client.move(e.key,("/".equals(prefix)?"":prefix)+n);runOnUiThread(this::load);}catch(Exception z){runOnUiThread(()->status.setText("Rename failed: "+z.getMessage()));}})).setNegativeButton("Cancel",null).show();}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
