package untrusted.manager.um.network;

import android.app.AlertDialog;
import android.content.Intent;
import android.os.Bundle;
import android.os.Environment;
import android.text.InputType;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.button.MaterialButton;
import java.io.File;
import java.util.*;
import java.util.concurrent.*;

public class SftpActivity extends AppCompatActivity {
    private static final int PICK=111;
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private final List<SftpClient.Entry> entries=new ArrayList<>();
    private final List<String> names=new ArrayList<>();
    private ArrayAdapter<String> adapter; private ListView list; private TextView path,status; private SftpClient client; private String current="/"; private android.content.SharedPreferences prefs;
    private String profilePrefsName(String base){String id=getIntent().getStringExtra("profile_id");return id==null||id.isEmpty()?base:base+"."+id;}
    @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences(profilePrefsName("sftp_profile"),MODE_PRIVATE); SecureNetworkPrefs.migrate(this,prefs,"pass","keyPassphrase"); build();}
    private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);MaterialToolbar bar=new MaterialToolbar(this);bar.setTitle("SFTP Storage");bar.setNavigationIcon(androidx.appcompat.R.drawable.abc_ic_ab_back_material);bar.setNavigationOnClickListener(v->finish());r.addView(bar);LinearLayout a=new LinearLayout(this);MaterialButton c=btn("Connect"),u=btn("Upload"),m=btn("New folder");c.setOnClickListener(v->connectDialog());u.setOnClickListener(v->pick());m.setOnClickListener(v->mkdir());a.addView(c,new LinearLayout.LayoutParams(0,-2,1));a.addView(u,new LinearLayout.LayoutParams(0,-2,1));a.addView(m,new LinearLayout.LayoutParams(0,-2,1));r.addView(a);path=new TextView(this);path.setPadding(16,12,16,8);path.setOnClickListener(v->up());r.addView(path);status=new TextView(this);status.setPadding(16,4,16,8);r.addView(status);list=new ListView(this);adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,names);list.setAdapter(adapter);list.setOnItemClickListener((p,v,pos,id)->{SftpClient.Entry e=entries.get(pos);if(e.directory){current=e.path;load();}else download(e);});list.setOnItemLongClickListener((p,v,pos,id)->{menu(entries.get(pos));return true;});r.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);showPath();}
    private MaterialButton btn(String s){MaterialButton b=new MaterialButton(this);b.setText(s);return b;}
    private EditText f(String value,String hint,boolean secret){EditText e=new EditText(this);e.setSingleLine(true);e.setHint(hint);e.setText(value);if(secret)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}
    private void connectDialog(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(16,8,16,8);EditText host=f(getIntent().getStringExtra("profile_host")!=null?getIntent().getStringExtra("profile_host"):prefs.getString("host",""),"Host",false),port=f(getIntent().getStringExtra("profile_port")!=null?getIntent().getStringExtra("profile_port"):prefs.getString("port","22"),"Port",false),user=f(prefs.getString("user",""),"Username",false),pass=f(SecureNetworkPrefs.get(this,prefs,"pass",""),"Password",true),key=f(prefs.getString("key",""),"Private key path (optional)",false),kp=f(SecureNetworkPrefs.get(this,prefs,"keyPassphrase",""),"Key passphrase (optional)",true),root=f(prefs.getString("root","/"),"Initial path",false);CheckBox trust=new CheckBox(this);trust.setText("Trust any server host key (less secure)");trust.setChecked(prefs.getBoolean("trust",false));b.addView(host);b.addView(port);b.addView(user);b.addView(pass);b.addView(key);b.addView(kp);b.addView(root);b.addView(trust);new AlertDialog.Builder(this).setTitle("Connect SFTP").setView(b).setPositiveButton("Connect",(d,w)->connect(host.getText().toString(),port.getText().toString(),user.getText().toString(),pass.getText().toString(),key.getText().toString(),kp.getText().toString(),root.getText().toString(),trust.isChecked())).setNegativeButton("Cancel",null).show();}
    private void connect(String h,String ps,String u,String pw,String key,String kp,String root,boolean trust){status.setText("Connecting…");io.execute(()->{try{int port=Integer.parseInt(ps.trim());SftpClient n=new SftpClient(h,port,u,pw,key,kp,trust,root);n.list(root);if(client!=null)client.close();client=n;current=root==null||root.trim().isEmpty()?"/":root;android.content.SharedPreferences.Editor pe=prefs.edit(); pe.putString("host",h).putString("port",ps).putString("user",u); SecureNetworkPrefs.put(pe,"pass",pw); SecureNetworkPrefs.put(pe,"keyPassphrase",kp); pe.putString("key",key).putString("root",current).putBoolean("trust",trust).apply();runOnUiThread(this::load);}catch(Exception e){runOnUiThread(()->status.setText("Connection failed: "+e.getMessage()));}});}
    private void showPath(){path.setText("Path: "+current+"  (tap to go up)");}
    private void up(){if(client==null||current.equals(client.getRoot()))return;int i=current.lastIndexOf('/');current=i<=0?client.getRoot():current.substring(0,i);load();}
    private void load(){showPath();if(client==null){status.setText("Not connected");return;}status.setText("Loading…");io.execute(()->{try{List<SftpClient.Entry> x=client.list(current);runOnUiThread(()->{entries.clear();entries.addAll(x);names.clear();for(SftpClient.Entry e:x)names.add((e.directory?"📁 ":"📄 ")+e.name+(e.symlink?" [link]":""));adapter.notifyDataSetChanged();status.setText(x.size()+" items");});}catch(Exception e){runOnUiThread(()->status.setText("Load failed: "+e.getMessage()));}});}
    private void pick(){if(client==null){toast("Connect first");return;}startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),PICK);}
    @Override protected void onActivityResult(int r,int result,Intent d){super.onActivityResult(r,result,d);if(r!=PICK||result!=RESULT_OK||d==null||d.getData()==null)return;android.net.Uri uri=d.getData();NetworkTransferQueue.get().submit("Upload", ()->{File tmp=new File(getCacheDir(),"sftp-upload-"+System.nanoTime());try(java.io.InputStream in=getContentResolver().openInputStream(uri);java.io.OutputStream out=new java.io.FileOutputStream(tmp)){if(in==null)throw new Exception("Cannot open source");byte[] buf=new byte[65536];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);String name=new File(uri.getPath()==null?"upload":uri.getPath()).getName();if(name.isEmpty()||name.contains(":"))name="upload";client.upload(tmp,(current.endsWith("/")?current:current+"/")+name);tmp.delete();runOnUiThread(this::load);}catch(Exception e){tmp.delete();runOnUiThread(()->status.setText("Upload failed: "+e.getMessage()));}});}
    private void download(SftpClient.Entry e){File dir=Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);if(!dir.exists())dir.mkdirs();File out=new File(dir,e.name);if(out.exists())out=new File(dir,System.currentTimeMillis()+"-"+e.name);File target=out;status.setText("Downloading…");NetworkTransferQueue.get().submit("Download", ()->{try{client.download(e.path,target);runOnUiThread(()->status.setText("Downloaded: "+target.getAbsolutePath()));}catch(Exception x){runOnUiThread(()->status.setText("Download failed: "+x.getMessage()));}});}
    private void mkdir(){if(client==null){toast("Connect first");return;}EditText e=f("","Folder name",false);new AlertDialog.Builder(this).setTitle("New SFTP folder").setView(e).setPositiveButton("Create",(d,w)->io.execute(()->{try{String n=e.getText().toString().trim();validate(n);client.mkdir(join(current,n));runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->status.setText("Create failed: "+x.getMessage()));}})).setNegativeButton("Cancel",null).show();}
    private void menu(SftpClient.Entry e){String[] items=e.directory?new String[]{"Delete","Rename"}:new String[]{"Download","Delete","Rename"};new AlertDialog.Builder(this).setTitle(e.name).setItems(items,(d,w)->{if(!e.directory&&w==0)download(e);else if((e.directory&&w==0)||(!e.directory&&w==1))io.execute(()->{try{client.delete(e.path);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->status.setText("Delete failed: "+x.getMessage()));}});else rename(e);}).show();}
    private void rename(SftpClient.Entry e){EditText n=f(e.name,"New name",false);new AlertDialog.Builder(this).setTitle("Rename").setView(n).setPositiveButton("Rename",(d,w)->io.execute(()->{try{String x=n.getText().toString().trim();validate(x);client.rename(e.path,join(current,x));runOnUiThread(this::load);}catch(Exception z){runOnUiThread(()->status.setText("Rename failed: "+z.getMessage()));}})).setNegativeButton("Cancel",null).show();}
    private static String join(String p,String n){return (p.endsWith("/")?p:p+"/")+n;}
    private static void validate(String n){if(n.isEmpty()||n.equals(".")||n.equals("..")||n.indexOf('\0')>=0||n.indexOf('/')>=0||n.indexOf('\\')>=0)throw new IllegalArgumentException("Invalid name");}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override protected void onDestroy(){io.shutdownNow();if(client!=null)client.close();super.onDestroy();}
}
